def test_model_proc(fn):
    from keras.models import load_model
    
    IMAGE_SIZE = 64
    LEARN_RATE = 1.0e-4
    CH=3
    print(fn)
    if fn!="":
        # Model Architecture and Compilation
        model = load_model('S:/Project Code latest - Copy/Project Code latest - Copy/cell_model.h5', compile=False)
        
        img = Image.open(fn)
        img = img.resize((IMAGE_SIZE,IMAGE_SIZE))
        img = np.array(img)
        
        img = img.reshape(1,IMAGE_SIZE,IMAGE_SIZE,3)
        
        img = img.astype('float32')
        img = img / 255.0
        print('img shape:',img)
        prediction = model.predict(img)
        print(np.argmax(prediction))
        cell=np.argmax(prediction)
        print(cell)
        
        if cell == 0:
            Cd="Sickeled Cell Detected \n Doctor Consultation Required \nReport Generated by (laboratory name) \n ---End of Report--- "
            
        elif cell == 1:
            Cd="LYMPHOCYTE Deficiency Detected\n Doctor Consultation Required \nReport Generated by (laboratory name) \n ---End of Report--- "
            
        elif cell == 2:
            Cd="MONOCYTE Deficiency Detected\n Doctor Consultation Required \nReport Generated by (laboratory name) \n ---End of Report--- "
            
        elif cell == 3:
            Cd="NEUTROPHIL Cell Detected \n Doctor Consultation Required \nReport Generated by (laboratory name) \n ---End of Report--- "
      
        A=Cd
        return A
    else:
        return "Please select a valid image."




# def clear_img():
    
#     img11 = tk.Label(frame_display, background='lightblue4',width=160,height=120)
#     img11.place(x=0, y=0)

def update_label(str_T):
    #clear_img()
    result_label = tk.Label(root, text=str_T, width=60, font=("bold", 25), bg='bisque2', fg='black')
    result_label.place(x=290, y=420)
# def train_model():
    
#     update_label("Model Training Start...............")
    
#     start = time.time()

#     X=Model_frm.main()
    
#     end = time.time()
        
#     ET="Execution Time: {0:.4} seconds \n".format(end-start)
    
#     msg="Model Training Completed.."+'\n'+ X + '\n'+ ET

#     update_label(msg)

def test_model():
    global fn
    if fn != "":
        update_label("Model Testing Start...............")
        
        start = time.time()
    
        X, percentage_detected = test_model_proc(fn)
        
        end = time.time()
            
        ET = "Detected Cell Percentage: {:.2f}% \n".format(percentage_detected)
        
        msg = "Image Testing Completed.."+'\n'+ X + '\n'+ ET
    else:
        msg = "Please Select Image For Prediction...."
        
    update_label(msg)